CREATE SEQUENCE IF NOT EXISTS plan_seq 
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999 
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS invoice_seq 
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999 
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS payment_seq 
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999 
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS contract_seq 
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999 
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS receipt_seq 
    START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999 
    CACHE 1;